import * as React from 'react';
import { Fingerprint, Radio, ScrollText, Wallet } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

import { Section } from '@/components/shared/section';
import { Card, CardContent } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';

/**
 * Transparency centrepiece.
 *
 * Plain language, technically precise, no marketing. Each column describes what
 * the platform actually does — the mechanism, the verification step and the
 * failure behaviour. Nothing here is a projection or a statistic, and no
 * guarantee is offered or implied.
 */

/** Paragraphs are JSX fragments, which have no natural id — hence the key. */
interface Paragraph {
  key: string;
  body: React.ReactNode;
}

interface Column {
  icon: LucideIcon;
  title: string;
  paragraphs: Paragraph[];
  facts: string[];
}

const COLUMNS: readonly Column[] = [
  {
    icon: Wallet,
    title: 'Crypto settlement — NOWPayments',
    paragraphs: [
      {
        key: 'address',
        body: (
          <>
            A deposit starts on your side of the wire. When you request one, the platform mints its
            own deposit identifier first and sends it to NOWPayments as the payment&rsquo;s{' '}
            <span className="text-base-100">order_id</span>, then stores the provider&rsquo;s payment
            id and the <span className="text-base-100">unique pay address</span> returned for that
            payment. The address belongs to that single payment, so a transfer lands against one
            order.
          </>
        ),
      },
      {
        key: 'signature',
        body: (
          <>
            Nothing is credited on the strength of a webhook&rsquo;s claim. Each IPN callback is
            verified against an <span className="text-base-100">HMAC-SHA512</span> signature
            computed over the exact raw request body (canonicalised as key-sorted JSON) and compared
            with a constant-time equality check. A callback that fails verification is rejected and
            written to the audit log without touching the deposit row, and a replayed callback is
            discarded by a one-shot claim.
          </>
        ),
      },
    ],
    facts: [
      'A deposit is credited only when the provider reports the payment confirmed on chain.',
      'The deposit id is generated by the platform and doubles as the provider order id, so a payment is still matchable if the payment id lookup fails.',
      'Invalid and replayed callbacks never mutate a balance.',
    ],
  },
  {
    icon: Radio,
    title: 'Broker connectivity — Deriv',
    paragraphs: [
      {
        key: 'execution',
        body: (
          <>
            Autopipsz is not a venue and does not run a matching engine. Orders are submitted to
            a <span className="text-base-100">Deriv</span> account over Deriv&rsquo;s WebSocket API,
            which talks to the broker&rsquo;s own trade server. Fills and settlements come back as
            <span className="text-base-100">broker-reported contracts</span> — the only source of
            P/L this platform accepts.
          </>
        ),
      },
      {
        key: 'mirroring',
        body: (
          <>
            A master account trades the strategy. Positions are mirrored into each funded
            investment by a lot allocator that floors the volume down to the symbol&rsquo;s volume
            step and tags the broker comment with an investment id, so a fill can be traced back to
            the capital that funded it. Every signal passes the pre-trade risk gate before an order
            is built.
          </>
        ),
      },
    ],
    facts: [
      'Client Lot Size = Master Lot Size × (Client Investment Capital / Master Account Equity)',
      'Volume is always floored down to the broker’s lot step — never rounded up, which would grant more exposure than the ratio allows.',
      'An allocation that cannot be produced honestly is skipped with a recorded reason instead of being approximated.',
    ],
  },
  {
    icon: ScrollText,
    title: 'Record integrity — ledger and audit log',
    paragraphs: [
      {
        key: 'equity',
        body: (
          <>
            Equity is not a running total that drifts; it is recomputed from an explicit formula over
            persisted ledger rows. Deployed capital and idle cash are a partition of contributed
            capital, so depositing and then allocating to a strategy is equity-neutral.
          </>
        ),
      },
      {
        key: 'audit',
        body: (
          <>
            Every state change that touches money, identity or the broker is written to an
            append-only audit log with a namespaced action, the details of the change and the actor.
            Identity documents are encrypted at rest with AES-256-GCM and held in the platform’s own
            database; they are read only through a signed-in administrator’s audited route, which
            streams the decrypted bytes and records the access.
          </>
        ),
      },
    ],
    facts: [
      'Equity = Starting Capital + Realized P/L + Unrealized P/L − Deducted Fees − Withdrawals + Confirmed Deposits',
      'Append-only audit log covering deposit, withdrawal, investment, broker, risk and KYC events.',
      'KYC files are encrypted at rest with AES-256-GCM and stored in the platform’s own database; only an ADMIN can open them, and every read is audited.',
    ],
  },
];

export interface TransparencyProps {
  className?: string;
}

export function Transparency({ className }: TransparencyProps) {
  return (
    <Section
      id="transparency"
      width="wide"
      eyebrow="Transparency"
      title="What happens to your money, mechanically"
      description="Three layers carry the whole platform: crypto settlement, broker execution and the record that ties them together. Each is described below the way it is built."
      className={className}
    >
      <div className="grid gap-5 lg:grid-cols-3">
        {COLUMNS.map((column) => {
          const Icon = column.icon;
          return (
            <Card key={column.title} className="flex flex-col">
              <CardContent className="flex flex-1 flex-col gap-4 p-5">
                <div className="flex items-center gap-3">
                  <span className="inline-flex size-9 shrink-0 items-center justify-center rounded-lg border border-line bg-base-800 text-brand-400">
                    <Icon className="size-4" />
                  </span>
                  <h3 className="text-[1rem] font-semibold leading-tight tracking-tight text-base-100">
                    {column.title}
                  </h3>
                </div>

                <div className="flex flex-col gap-3 text-sm leading-relaxed text-muted">
                  {column.paragraphs.map((paragraph) => (
                    <p key={paragraph.key}>{paragraph.body}</p>
                  ))}
                </div>

                <Separator className="mt-auto" />

                <ul className="flex flex-col gap-2 text-xs leading-relaxed text-muted">
                  {column.facts.map((fact) => (
                    <li key={fact} className="flex gap-2">
                      <Fingerprint aria-hidden className="mt-0.5 size-3 shrink-0 text-brand-400" />
                      <span>{fact}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </Section>
  );
}
