'use strict';

module.exports = {
  MAX_LENGTH: 10000,
  CHAR_BACKSLASH: '\\',
  CHAR_BACKTICK: '`',
  CHAR_COMMA: ',',
  CHAR_DOT: '.',
  CHAR_LEFT_PARENTHESES: '(',
  CHAR_RIGHT_PARENTHESES: ')',
  CHAR_LEFT_CURLY_BRACE: '{',
  CHAR_RIGHT_CURLY_BRACE: '}',
  CHAR_LEFT_SQUARE_BRACKET: '[',
  CHAR_RIGHT_SQUARE_BRACKET: ']',
  CHAR_DOUBLE_QUOTE: '"',
  CHAR_SINGLE_QUOTE: "'",
  CHAR_NO_BREAK_SPACE: '\u00A0',
  CHAR_ZERO_WIDTH_NOBREAK_SPACE: '\uFEFF'
};