/** Frontend-safe copy of the server AUDIT action registry. */
export const AUDIT = {
  // auth
  AUTH_REGISTERED: 'AUTH_REGISTERED',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_2FA_ENABLED: 'AUTH_2FA_ENABLED',
  AUTH_2FA_DISABLED: 'AUTH_2FA_DISABLED',
  AUTH_2FA_CHALLENGE_FAILED: 'AUTH_2FA_CHALLENGE_FAILED',
  AUTH_TOKEN_REFRESHED: 'AUTH_TOKEN_REFRESHED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_CHANGE_FAILED: 'AUTH_PASSWORD_CHANGE_FAILED',

  // kyc
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_RESUBMITTED: 'KYC_RESUBMITTED',
  KYC_REVIEW_STARTED: 'KYC_REVIEW_STARTED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_ADDITIONAL_INFO_REQUESTED: 'KYC_ADDITIONAL_INFO_REQUESTED',
  KYC_DOCUMENT_VIEWED: 'KYC_DOCUMENT_VIEWED',

  // payments in
  DEPOSIT_CREATED: 'DEPOSIT_CREATED',
  DEPOSIT_IPN_RECEIVED: 'DEPOSIT_IPN_RECEIVED',
  DEPOSIT_IPN_REJECTED: 'DEPOSIT_IPN_REJECTED',
  DEPOSIT_CONFIRMED: 'DEPOSIT_CONFIRMED',
  /**
   * A deposit CREDITED BY AN OPERATOR, not by a payment provider.
   *
   * Its own action on purpose: the money is real in the ledger, but no chain
   * payment happened, and an audit trail that files it under DEPOSIT_CONFIRMED
   * would claim a settlement the platform never received.
   */
  ADMIN_DEPOSIT_CREDITED: 'ADMIN_DEPOSIT_CREDITED',
  DEPOSIT_FAILED: 'DEPOSIT_FAILED',

  // payments out
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_BROADCAST: 'WITHDRAWAL_BROADCAST',
  WITHDRAWAL_FAILED: 'WITHDRAWAL_FAILED',

  // investments
  INVESTMENT_CREATED: 'INVESTMENT_CREATED',
  /**
   * An OPERATOR deployed a client's funds into a plan on their behalf.
   *
   * Its own action because the client did not click anything: the audit row must
   * name the operator, their stated reason, and the client's KYC status at the
   * moment of the decision — otherwise the trail implies a client action that
   * never happened, and hides that an unverified account was funded.
   */
  ADMIN_INVESTMENT_CREATED: 'ADMIN_INVESTMENT_CREATED',
  INVESTMENT_ACTIVATED: 'INVESTMENT_ACTIVATED',
  INVESTMENT_PAUSED: 'INVESTMENT_PAUSED',
  INVESTMENT_CLOSED: 'INVESTMENT_CLOSED',
  INVESTMENT_MATURED: 'INVESTMENT_MATURED',

  // internally-executed positions (EXECUTION_MODE=internal)
  POSITION_OPENED: 'POSITION_OPENED',
  POSITION_CLOSED: 'POSITION_CLOSED',

  // broker
  BROKER_CONNECTED: 'BROKER_CONNECTED',
  BROKER_DISCONNECTED: 'BROKER_DISCONNECTED',
  BROKER_ERROR: 'BROKER_ERROR',
  BROKER_ADDED: 'BROKER_ADDED',
  BROKER_ORDER_SUBMITTED: 'BROKER_ORDER_SUBMITTED',
  BROKER_ORDER_FILLED: 'BROKER_ORDER_FILLED',
  BROKER_ORDER_REJECTED: 'BROKER_ORDER_REJECTED',
  BROKER_POSITION_CLOSED: 'BROKER_POSITION_CLOSED',

  // risk / bot
  RISK_CHECK_PASSED: 'RISK_CHECK_PASSED',
  RISK_CHECK_FAILED: 'RISK_CHECK_FAILED',
  RISK_DRAWDOWN_BREACH: 'RISK_DRAWDOWN_BREACH',
  RISK_KILL_SWITCH: 'RISK_KILL_SWITCH',
  BOT_SIGNAL_TRIGGERED: 'BOT_SIGNAL_TRIGGERED',
  BOT_STARTED: 'BOT_STARTED',
  BOT_STOPPED: 'BOT_STOPPED',
  LOT_ALLOCATED: 'LOT_ALLOCATED',
  /**
   * One per investment on every stake-sized signal, including the skipped ones.
   * Separate from LOT_ALLOCATED because the numbers mean different things: a
   * stake is money at risk, a lot is a size, and an audit trail that blurs them
   * cannot answer "how much was put at risk".
   */
  STAKE_ALLOCATED: 'STAKE_ALLOCATED',

  // admin
  PLAN_CREATED: 'PLAN_CREATED',
  PLAN_UPDATED: 'PLAN_UPDATED',
  PLAN_DEACTIVATED: 'PLAN_DEACTIVATED',
  ADMIN_USER_ROLE_CHANGED: 'ADMIN_USER_ROLE_CHANGED',
  ADMIN_SETTINGS_UPDATED: 'ADMIN_SETTINGS_UPDATED',
  ADMIN_TRADE_FORCE_CLOSED: 'ADMIN_TRADE_FORCE_CLOSED',
} as const;
